---
# tasks file for ansible-role-podman

- name: Include OS specific variables.
  include_vars: "{{ ansible_os_family }}.yml"

- name: Install Podman
  include_tasks: "setup-{{ ansible_os_family }}.yml"
