---
# tasks file for ansible-role-podman

- name: Include OS specific variables.
  include_vars: "{{ ansible_os_family }}.yml"

- name: Linux | Install Podman
  include_tasks: "setup-{{ ansible_distribution }}.yml"
  when: ansible_distribution == "Amzonlinux" or
        ansible_distribution == "Debian" or
        ansible_distribution == "Ubuntu"

- name: Linux | Install Podman
  package:
    name: "{{ podman_package }}"
    state: present

- name: Linux | Configure rootless users
  include_tasks: "rootless.yml"
  when: rootless_users | length > 0
