---
- name: Ubuntu 20.04 | Install kubic apt key
  apt_key:
    url: "https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_20.04/Release.key"
    state: present

- name: Ubuntu 20.04 | Install kubic repository
  apt_repository:
    repo: "deb https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_20.04/ /"
    state: present
