---
- name: Converge
  hosts: all
  tasks:
    - name: "Include ansible-role-podman"
      include_role:
        name: "ansible-role-podman"
      vars:
        rootless_users: "{{ lookup('env', 'rootless_users') | default([], true) }}"
