---
- name: Prepare
  hosts: all
  tasks:
    - name: Archlinux | Update pacman cache
      pacman:
        update_cache: yes
      when: ansible_pkg_mgr == "pacman"

    - name: Linux | Create rootless user
      user:
        name: johnd
        comment: John Doe
        state: present
