name: molecule

on:
  push:
  pull_request: 
  schedule:
    - cron: '0 18 * * sun'

jobs:
  build:
    name: ${{ matrix.image }}
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        image:
          - ansible-archlinux:latest
          - ansible-amazonlinux:2
          - ansible-centos:8
          - ansible-centos:7
          - ansible-debian:10
          - ansible-fedora:32
          - ansible-fedora:31
          - ansible-fedora:30
          - ansible-fedora:29
          - ansible-fedora:28
          - ansible-fedora:27
          - ansible-opensuse:leap
          - ansible-opensuse:tumbleweed
          - ansible-opensuse:15
          - ansible-opensuse:15.1
          - ansible-oraclelinux:8
          - ansible-ubuntu:18.04
          - ansible-ubuntu:20.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install Molecule
        run: |
          python -m pip install --upgrade pip
          pip install ansible ansible-lint molecule-docker docker

      - name: Test Ansible role
        run: molecule test
        env:
          image: ${{ matrix.image }}

      - name: Test Ansible role with check_mode enable
        run: molecule check
        env:
          image: ${{ matrix.image }}
